export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const AUTH = "AUTH";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_PROFILE = "GET_PROFILE";
export const GET_AVATAR = "GET_AVATAR";

export const PROFILE_ERROR = "PROFILE_ERROR";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";

export const CREATE_BOOK = "CREATE_BOOK";
export const FETCH_BY_SEARCH = "FETCH_BY_SEARCH";
export const FETCH_BOOK = "FETCH_BOOK";
export const FETCH_BOOKS = "FETCH_BOOKS";
export const UPDATE_BOOK = "UPDATE_BOOK";
export const DELETE_BOOK = "DELETE_BOOK";

export const SELECT_BOOK = "SELECT_BOOK";
export const ASK_QUESTION = "ASK_QUESTION";
export const ASK_QUESTION_FAIL = "ASK_QUESTION_FAIL";
export const ANSWER_SUCCESS = "ANSWER_SUCCESS";
export const SOURCE_SUCCESS = "SOURCE_SUCCESS";
export const SAVE_ANSWER = "SAVE_ANSWER";
export const RESET_QUESTION = "RESET_QUESTION";

export const GET_QUESTION = "GET_QUESTION_ALL";
export const GET_QUESTION_USER = "GET_QUESTION_USER";
export const GET_QUESTION_BOOK = "GET_QUESTION_BOOK";
export const GET_QUESTION_COUNT = "GET_QUESTION_COUNT";

export const SELECT_POST = "SELECT_POST";
export const SAVE_COMMENT = "SAVE_COMMENT";
export const GET_COMMENT = "GET_COMMENT";
export const GET_QUESTION_ID = "GET_QUESTION_ID";
export const LOAD_AVATAR = "LOAD_AVATAR";
export const CLEAR_QUESTION_USER = "CLEAR_QUESTION_USER";
export const GET_RECOMMEND = "GET_RECOMMEND";
export const CLEAR_RECOMMEND = "CLEAR_RECOMMEND";
